# This code is part of Qiskit.
#
# (C) Copyright IBM 2021, 2022.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Finance'
description: 'Installs Qiskit Finance on developer mode'
inputs:
  os:
    description: 'OS'
    required: true
runs:
  using: "composite"
  steps: 
    - run : |
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate scsenv
        fi
        pip install -e .
        pip install qiskit-optimization[cplex,cvx]
        pip install -U -c constraints.txt -r requirements-dev.txt
      shell: bash
