# This code is part of a Qiskit project.
#
# (C) Copyright IBM 2021, 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Finance Main Dependencies'
description: 'Installs Python dependencies from Main'
inputs:
  os:
    description: 'OS'
    required: true
  python-version:
    description: 'Python version'
    required: true
  qiskit-main:
    description: 'Use Qiskit main'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get main last commit ids
      run: |
        echo "QISKIT_HASH=$(git ls-remote --heads https://github.com/Qiskit/qiskit.git refs/heads/main  | awk '{print $1}')" >> $GITHUB_ENV
        echo "OPTIMIZATION_HASH=$(git ls-remote --heads https://github.com/qiskit-community/qiskit-optimization.git refs/heads/main  | awk '{print $1}')" >> $GITHUB_ENV
      shell: bash
    - name: Qiskit Cache
      env:
        CACHE_VERSION: v1
      id: qiskit-cache
      uses: actions/cache@v4
      with:
        path: qiskit-cache
        key: qiskit-cache-${{ inputs.os }}-${{ inputs.python-version }}-${{ env.QISKIT_HASH }}-${{ env.CACHE_VERSION }}
    - name: Optimization Cache
      env:
        CACHE_VERSION: v1
      id: optimization-cache
      uses: actions/cache@v4
      with:
        path: optimization-cache
        key: optimization-cache-${{ inputs.os }}-${{ inputs.python-version }}-${{ env.OPTIMIZATION_HASH }}-${{ env.CACHE_VERSION }}
    - name: Install Qiskit from Main
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
      run: |
        if [ "${{ inputs.qiskit-main }}" == "true" ]; then
          echo 'Install Qiskit from Main'
          if [ "${{ inputs.os }}" == "windows-latest" ]; then
            source "$CONDA/etc/profile.d/conda.sh"
            conda activate scsenv
          fi
          BASE_DIR=qiskit-cache
          build_from_main=true
          cache_hit=${{ steps.qiskit-cache.outputs.cache-hit }}
          echo "cache hit: ${cache_hit}"
          if [ "$cache_hit" == "true" ]; then
            pip_result=0
            pushd "${BASE_DIR}"
            python -m pip install *.whl && pip_result=$? || pip_result=$?
            popd
            if [ $pip_result == 0 ]; then
              build_from_main=false
            fi
          else
            mkdir -p ${BASE_DIR}
          fi
          if [ "$build_from_main" == "true" ]; then
            echo 'Create wheel file from main'
            pip install -U wheel setuptools_rust
            git clone --depth 1 --branch main https://github.com/Qiskit/qiskit.git /tmp/qiskit
            pushd /tmp/qiskit
            python setup.py bdist_wheel
            popd
            cp -rf /tmp/qiskit/dist/*.whl "${BASE_DIR}"
            pushd "${BASE_DIR}"
            python -m pip install *.whl
            popd
            pip uninstall -y setuptools_rust
          fi
        else
          echo 'Install Qiskit from Stable'
          if [ "${{ inputs.os }}" == "windows-latest" ]; then
            source "$CONDA/etc/profile.d/conda.sh"
            conda activate scsenv
          fi
          pip install -U qiskit
        fi
      shell: bash
    - name: Install stable Aer
      run: |
        echo 'Install stable Aer'
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate scsenv
        fi
        pip install -U qiskit-aer
      shell: bash
    - name: Install Optimization from Main
      run: |
        echo 'Install Optimization from Main'
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate scsenv
        fi
        BASE_DIR=optimization-cache
        build_from_main=true
        cache_hit=${{ steps.optimization-cache.outputs.cache-hit }}
        echo "cache hit: ${cache_hit}"
        if [ "$cache_hit" == "true" ]; then
          pip_result=0
          pushd "${BASE_DIR}"
          python -m pip install *.whl && pip_result=$? || pip_result=$?
          popd
          if [ $pip_result == 0 ]; then
            build_from_main=false
          fi
        else
          mkdir -p ${BASE_DIR}
        fi
        if [ "$build_from_main" == "true" ]; then
          echo 'Create wheel file from main'
          pip install -U wheel
          pip install -U setuptools
          git clone --depth 1 --branch main https://github.com/qiskit-community/qiskit-optimization.git /tmp/qiskit-optimization
          pushd /tmp/qiskit-optimization
          python setup.py bdist_wheel
          popd
          cp -rf /tmp/qiskit-optimization/dist/*.whl "${BASE_DIR}"
          pushd "${BASE_DIR}"
          python -m pip install *.whl
          popd
        fi
      shell: bash
