# This code is part of Qiskit.
#
# (C) Copyright IBM 2021, 2022.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Finance Main Dependencies'
description: 'Installs Python dependencies from Main'
inputs:
  os:
    description: 'OS'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Dependencies from Main
      run: |
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate scsenv
        fi
        pip install git+https://github.com/Qiskit/qiskit-terra
        pip install git+https://github.com/Qiskit/qiskit-optimization
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          export DISABLE_CONAN=1
          sudo apt-get -y install nlohmann-json3-dev
          sudo apt-get -y install libspdlog-dev
          sudo apt-get -y install libmuparserx-dev
        fi
<<<<<<< HEAD
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          git clone https://github.com/Qiskit/qiskit-aer.git /tmp/qiskit-aer
          pushd /tmp/qiskit-aer
          python setup.py bdist_wheel -- -G 'Visual Studio 16 2019'
          pip install --find-links=dist qiskit-aer
=======
        git clone --depth 1 --branch main https://github.com/Qiskit/qiskit-aer.git /tmp/qiskit-aer
        BASE_DIR=aer-cache
        build_from_main=true
        cache_hit=${{ steps.aer-cache.outputs.cache-hit }}
        echo "cache hit: ${cache_hit}"
        if [ "$cache_hit" == "true" ]; then
          pip_result=0
          pushd "${BASE_DIR}"
          python -m pip install --upgrade --force-reinstall *.whl && pip_result=$? || pip_result=$?
          popd
          if [ $pip_result == 0 ]; then
            echo 'Verifying cached Aer with tools/verify_wheels.py ...'
            verify_result=0
            pushd /tmp/qiskit-aer
            python tools/verify_wheels.py && verify_result=$? || verify_result=$?
            popd
            if [ $verify_result == 0 ]; then
              echo 'Cached Aer passed verification.'
              build_from_main=false
            else
              echo 'Cached Aer failed verification.'
            fi
          fi
        else
          mkdir -p ${BASE_DIR}
        fi
        if [ "$build_from_main" == "true" ]; then
          echo 'Create wheel file from main'
          pip install -U wheel
          pushd /tmp/qiskit-aer
          if [ "${{ inputs.os }}" == "windows-2019" ]; then
            python setup.py bdist_wheel -- -G 'Visual Studio 16 2019'
          elif  [ "${{ inputs.os }}" == "macos-latest" ]; then
            pip install -U -c constraints.txt -r requirements-dev.txt
            python setup.py bdist_wheel --plat-name macosx-10.16-x86_64
          else
            python setup.py bdist_wheel
          fi
          popd
          cp -rf /tmp/qiskit-aer/dist/*.whl "${BASE_DIR}"
          pushd "${BASE_DIR}"
          python -m pip install --upgrade --force-reinstall *.whl
          popd
        fi
      shell: bash
    - name: Install Optimization from Main
      run: |
        echo 'Install Optimization from Main'
        if [ "${{ inputs.os }}" == "windows-2019" ]; then
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate scsenv
        fi
        BASE_DIR=optimization-cache
        build_from_main=true
        cache_hit=${{ steps.optimization-cache.outputs.cache-hit }}
        echo "cache hit: ${cache_hit}"
        if [ "$cache_hit" == "true" ]; then
          pip_result=0
          pushd "${BASE_DIR}"
          python -m pip install *.whl && pip_result=$? || pip_result=$?
>>>>>>> ca5a4a5 (Fix CI aer build (#228))
          popd
        else
          pip install git+https://github.com/Qiskit/qiskit-aer
        fi
      shell: bash
